# Generated by Django 4.2 on 2023-09-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_cart',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='cart',
            field=models.JSONField(default=dict),
        ),
    ]
