# Generated by Django 4.2 on 2023-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchased_books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('orderid', models.CharField(max_length=16)),
                ('book_title', models.CharField(max_length=100)),
                ('isbn', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=20)),
                ('saleOrBorrow', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('imgurl', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=700)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
