# Generated by Django 4.2 on 2023-09-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_purchased_books_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_books',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
